name: "shirakalu"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: masgeek/shirakalu:${TAG:-latest}
    container_name: shirakalu
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=your_database_name
      - DB_USER=root
      - DB_PASSWORD=your_password
    #    depends_on:
    #      - db

  db:
    image: bitnami/mariadb:11.4.2
    container_name: db
    hostname: db
    environment:
      mariadb_root_host: "%"
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME:-shirakalu}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    #    volumes:
    #      - db-data:/bitnami/mariadb

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8200:8080"

networks:
  web:

volumes:
  db-data:
    name: db-data