<?php

namespace app\models;

use \app\models\base\Operation as BaseOperation;

/**
 * This is the model class for table "operations".
 */
class Operation extends BaseOperation
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
