<?php

namespace app\models;

use \app\models\base\OperationRate as BaseOperationRate;

/**
 * This is the model class for table "operation_rates".
 */
class OperationRate extends BaseOperationRate
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
