<?php

namespace app\models;

use \app\models\base\RatesHistory as BaseRatesHistory;

/**
 * This is the model class for table "rates_history".
 */
class RatesHistory extends BaseRatesHistory
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
