<?php

namespace app\models;

use \app\models\base\StaffType as BaseStaffType;

/**
 * This is the model class for table "staff_type".
 */
class StaffType extends BaseStaffType
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
