<?php

namespace app\models;

use \app\models\base\Staff as BaseStaff;

/**
 * This is the model class for table "staff".
 */
class Staff extends BaseStaff
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
