<?php

namespace app\models;

use \app\models\base\User as BaseUser;

/**
 * This is the model class for table "users".
 */
class User extends BaseUser
{
    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }


    /**
     * Generates "remember me" authentication key
     * @throws \yii\base\Exception
     */
    public function generateAuthKey(): void
    {
        $this->auth_key = \Yii::$app->security->generateRandomString();
    }
}
